---
- name: Copy kubeadm config
  copy:
    src: kubeadm-config.yaml
    dest: /home/ubuntu/kubeadm-config.yaml
- name: Run kubeadm init
  shell: |
    kubeadm init --config=kubeadm-config.yaml --upload-certs
  become: true