---
- name: Copy kubeadm config
  copy:
    src: kubeadm-config.yaml
    dest: /home/ubuntu/kubeadm-config.yaml
- name: Copy calico config
  copy:
    src: calico.yaml
    dest: /home/ubuntu/calico.yaml
- name: Run kubeadm init
  shell: |
    kubeadm init --config=kubeadm-config.yaml --upload-certs
  become: true
- name: 'initialize | create kubectl config directory'
  file:
    path: '/home/ubuntu/.kube/'
    state: 'directory'
    owner: 'ubuntu'
    group: 'ubuntu'
    mode: 0750

- name: 'initialize | copy admin.conf to kubectl config directory'
  copy:
    src: '/etc/kubernetes/admin.conf'
    dest: '/home/ubuntu/.kube/config'
    owner: 'ubuntu'
    group: 'ubuntu'
    mode: 0750
    remote_src: true
    backup: true

- name: 'initialize | copy Kubernetes config locally'
  fetch:
    src: '/etc/kubernetes/admin.conf'
    dest: '/home/ubuntu/.kube/config'
    flat: true
- name: Run calico init
  shell: |
    kubectl apply -f calico.yaml