---
- name: Copy kubeadm config
  copy:
    src: kubeadm-config.yaml
    dest: /home/ubuntu/kubeadm-config.yaml
- name: Run kubeadm init
  shell: |
    kubeadm init --config=kubeadm-config.yaml --upload-certs
  become: true
- name: 'initialize | create kubectl config directory'
  ansible.builtin.file:
    path: '/ubuntu/.kube/'
    state: 'directory'
    owner: 'ubuntu'
    group: 'ubuntu'
    mode: 0750

- name: 'initialize | copy admin.conf to kubectl config directory'
  ansible.builtin.copy:
    src: '/etc/kubernetes/admin.conf'
    dest: '/ubuntu/.kube/config'
    owner: 'ubuntu'
    group: 'ubuntu'
    mode: 0750
    remote_src: true
    backup: true

- name: 'initialize | copy Kubernetes config locally'
  ansible.builtin.fetch:
    src: '/etc/kubernetes/admin.conf'
    dest: '/ubuntu/.kube/config'
    flat: true